# Configurações do Servidor
server.port=8080

# Configurações do Banco de Dados Oracle (usando variáveis de ambiente)
spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:oracle.fiap.com.br}:${DB_PORT:1521}:${DB_SID:ORCL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de Segurança (JWT)
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000

# Configurações do Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
